---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: centos-6
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    require_chef_omnibus: 11.8
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: 11.8

suites:
- name: default
  run_list:
  - recipe[jira_test]
  attributes: {}
- name: standalone-postgresql
  run_list:
  - recipe[jira_test]
  attributes:
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true
    jira:
      install_type: standalone
      database:
        type: postgresql
        host: localhost
        port: 5432
